name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - name: darwin-arm64
            os: macos-14
            target: aarch64-apple-darwin
          - name: darwin-x64
            os: macos-14
            target: x86_64-apple-darwin
          - name: linux-arm64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
          - name: linux-x64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - name: windows-arm64
            os: windows-2022
            target: aarch64-pc-windows-msvc
            ext: .exe
          - name: windows-x64
            os: windows-2022
            target: x86_64-pc-windows-msvc
            ext: .exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform.target }}-${{ github.sha }}

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Copy binary to package
        run: |
          mkdir -p packages/hono-kit-${{ matrix.platform.name }}/bin
          cp target/${{ matrix.platform.target }}/release/hono-kit${{ matrix.platform.ext }} packages/hono-kit-${{ matrix.platform.name }}/bin/

      - name: Upload Release Binary
        uses: actions/upload-artifact@v4
        with:
          name: hono-kit-${{ matrix.platform.name }}
          path: target/${{ matrix.platform.target }}/release/hono-kit${{ matrix.platform.ext }}

  commit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download binaries
        run: |
          for target in darwin-arm64 darwin-x64 linux-arm64 linux-x64 windows-arm64 windows-x64; do
            gh run download -n hono-kit-$target -D packages/hono-kit-$target/bin/
          done
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: -f packages/**/bin/hono-kit*
          author_name: hono-kit-build-bot
          message: "ci: update binary for all targets"
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
