name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - name: linux-x64-glibc
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - name: linux-arm64-glibc
            os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
          - name: win32-x64-msvc
            os: windows-2022
            target: x86_64-pc-windows-msvc
          - name: win32-arm64-msvc
            os: windows-2022
            target: aarch64-pc-windows-msvc
          - name: darwin-x64
            os: macos-14
            target: x86_64-apple-darwin
          - name: darwin-arm64
            os: macos-14
            target: aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform.target }}-${{ github.sha }}

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Upload Release Binary
        uses: actions/upload-artifact@v4
        with:
          name: hono-kit-${{ matrix.platform.name }}
          path: target/${{ matrix.platform.target }}/release/hono-kit